# Generated by Django 2.2.3 on 2020-08-11 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_auto_20200811_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='next_evolutions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon_entities.Pokemon'),
        ),
    ]
