# Generated by Django 2.2.3 on 2020-08-11 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_pokemon_next_evolutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='next_evolutions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolutions', to='pokemon_entities.Pokemon'),
        ),
    ]
